In [5]:
!python3 cli/finance.py -ti AAPL -fi data/aapl.csv

#### Fama-French dataset

[[1]](https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html) Dartmouth College, French, K.R (2025) *Current Research Returns* Available at: https://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html (Accessed: 17 December 2025)

In [ ]:
from pandas import DataFrame, read_csv

path: str = "data/F-F_Research_Data_5_Factors_2x3_daily.csv"
fama_french: DataFrame = read_csv(path)

fama_french.index = fama_french.index.astype("int32")

In [ ]:
from pandas import DataFrame, Series, read_csv, to_datetime

path: str = "data/aapl.csv"
ticker: DataFrame = read_csv(path)
ticker.index = to_datetime(ticker.index, utc = True).strftime("%Y%m%d")
ticker.index = ticker.index.astype("int32")

returns: Series = ticker["Close"].pct_change() * 100
returns.dropna(inplace = True)

In [6]:
from pandas import merge, DataFrame

data: DataFrame = merge(returns, fama_french, how = "inner", left_index = True, right_index = True)
data.to_csv("data/fama_french_data.csv", index = False)

In [ ]:
from pandas import DataFrame
from sklearn.model_selection import TimeSeriesSplit
import numpy as np

data: DataFrame = read_csv("data/fama_french_data.csv")
x: DataFrame = data[data.columns[1:]]
y: DataFrame = data[["Close"]]

split: TimeSeriesSplit = TimeSeriesSplit(n_splits = 8)

for fold, (train_index, test_index) in enumerate(split.split(x)):
  x_train: np.ndarray = np.array(train_index)
  x_test: np.ndarray = np.array(test_index)
  y_train: np.ndarray = np.array(train_index)
  y_test: np.ndarray = np.array(test_index)

[1257 1258 1259 ... 2511 2512 2513]
[2514 2515 2516 ... 3768 3769 3770]
[3771 3772 3773 ... 5025 5026 5027]
[5028 5029 5030 ... 6282 6283 6284]
[6285 6286 6287 ... 7539 7540 7541]
[7542 7543 7544 ... 8796 8797 8798]
[ 8799  8800  8801 ... 10053 10054 10055]
[10056 10057 10058 ... 11310 11311 11312]
